/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_lyrichu_java_jni_HelloWorld */

#ifndef _Included_pers_lyrichu_java_jni_HelloWorld
#define _Included_pers_lyrichu_java_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_lyrichu_java_jni_HelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pers_lyrichu_java_jni_HelloWorld_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
