/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_lyrichu_java_jni_func_SimpleFuncWithParams */

#ifndef _Included_pers_lyrichu_java_jni_func_SimpleFuncWithParams
#define _Included_pers_lyrichu_java_jni_func_SimpleFuncWithParams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_lyrichu_java_jni_func_SimpleFuncWithParams
 * Method:    integerSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pers_lyrichu_java_jni_func_SimpleFuncWithParams_integerSum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pers_lyrichu_java_jni_func_SimpleFuncWithParams
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pers_lyrichu_java_jni_func_SimpleFuncWithParams_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
